nelmio_api_doc:
    documentation:
        info:
            title: Siroko Test App
            description: This is an awesome app!
            version: 1.0.0
        tags:
            - name: 'Health Check'
              description: 'Endpoints related to verifying the status and availability of the service.'
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/openapi$) # Accepts routes under /api except /api/doc
