services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shopping\:
        resource: '../../../'
        exclude:
            - '../../../Infrastructure/Symfony/DependencyInjection/'
