parameters:
    app.locale_default: '%env(LANGUAGE_DEFAULT)%'
    app.locale_list: '%env(LANGUAGE_LIST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\:
        resource: '../../../'

    App\Shared\Infrastructure\UI\Console\:
        resource: '../../../Infrastructure/UI/Console/'
        tags: ['console.command']
